name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-ip-reverse-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials reverseip --zone us-central1-a --project flaskreverseip

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
     
      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Helm upgrade and install
        run: helm upgrade --install flask-ip-reverse-app ./flask-ip-reverse-app --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask-ip-reverse-app,image.tag=${{ github.sha }}
